config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks/new', to: 'tasks#new', as: 'newt'
  get 'tasks', to: 'tasks#index'
  get 'tasks/:id', to: 'tasks#show', as: 'task'
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit'
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy', as: 'delete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to tasks_path(@tasks)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    # => Whitelisting
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

   <%= f.label :completed %>
  <%= f.text_field :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form', restaurant: @restaurant %>

app/views/tasks/index.html.erb
<h1> HELLO </h1>
<%= link_to "Create a new task", newt_path %>
<% @tasks.each do |task| %>
<h2><%= task.title %></h2>
<p><%= task.completed %></p>
<%= link_to "Delete.", task_path(task), method: :delete, data:{confirm: "R u sure ?"} %>
<%= link_to task.title, task_path(task) %>
<% end %>

app/views/tasks/new.html.erb
<%= render 'form', restaurant: @restaurant %>

app/views/tasks/show.html.erb
<h1> HELLO </h1>
<h2><%= @task.title %></h2>
<h3><%= @task.details %></h3>
<p><%= @task.completed %></p>
<%= link_to "Edit file ?", edit_path %>
<%= link_to "Back to the list !", tasks_path() %>